name: Update README
on:
  push:
    paths:
      - "**.js"
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update README
        run: |
          chmod +x update_readme.sh
          ./update_readme.sh
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Update README"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: "readme-update"
          delete-branch: true
          title: "Update README"
          body: "This PR updates the README file."
