name: Update README
on:
  push:
    paths:
      - "**.js"
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          title: "Update README"
          branch: "readme-update"
          commit-message: Update README
          labels: |
            report
            automated pr
          assignees: gthrm
          reviewers: gthrm
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: true
          milestone: 1
          draft: false
